apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.3.4 # Recommended: Check for the latest version
    helm:
      values: |
        configs:
          params:
            server.insecure: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # --- SYNC POLICY ---
  # Initially empty for safe adoption. 
  # Once synced manually, uncomment the automated block below.
  syncPolicy:
    automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
