apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nucky-networking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeatGrate/nucky-thompson-deployments
    targetRevision: initial-test
    path: infra/nucky-networking
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

