apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 38.0.2
    helm:
      values: |
        providers:
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
            gateway:
              listeners:
                - name: web
                  port: 80
                  protocol: HTTP
                - name: websecure
                  port: 443
                  protocol: HTTPS
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
