apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

destination:
  server: "https://kubernetes.default.svc"
  namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts # Traefik Helm chart repository URL
      chart: traefik
      targetRevision: v38.0.2 # Use a specific chart version (e.g., "  # Optional: Configure sync policy for automatic deployment
      helm:
        releaseName: traefik
        valueFiles:
          - $values/traefik/mi6.values.yaml

    - repoURL: https://github.com/BeatGrate/nucky-thompson-deployments
      targetRevision: initial-test
      ref: values

  syncPolicy:
    automated:
      prune: true # Allows ArgoCD to delete resources that are no longer in Git
      selfHeal: true # Allows ArgoCD to sync changes if the live state drifts from Git
    syncOptions:
      # Automatically create the destination namespace if it doesn't exist
      - CreateNamespace=true

